# Generated by Django 5.1.1 on 2024-10-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('examiner', 'Examiner')], default='mentor', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('submission_status', models.CharField(choices=[('green', 'Submitted'), ('red', 'Not Submitted')], default='red', max_length=10)),
                ('midsem_marks', models.IntegerField(default=0)),
                ('total_midsem_marks', models.IntegerField(default=0)),
                ('endsem_marks', models.IntegerField(default=0)),
                ('total_endsem_marks', models.IntegerField(default=0)),
                ('examiner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examined_students1', to=settings.AUTH_USER_MODEL)),
                ('examiner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examined_students2', to=settings.AUTH_USER_MODEL)),
                ('examiner3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examined_students3', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentored_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=100)),
                ('presentation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('project_title', models.CharField(max_length=200)),
                ('depth_of_understanding', models.IntegerField()),
                ('work_done_and_results', models.IntegerField()),
                ('exceptional_work', models.IntegerField()),
                ('viva_voce', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('report', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
