# Generated by Django 5.1.1 on 2024-10-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='presentation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='presentation_from_time',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='presentation_to_time',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='project_title',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
