# Generated by Django 5.1.1 on 2024-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_remove_student_email_remove_student_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
