# Generated by Django 5.1.1 on 2024-10-03 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_student_email_student_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
    ]
