# Generated by Django 5.1.1 on 2024-10-03 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_professor_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="phone",
        ),
    ]
