# Generated by Django 5.1.1 on 2024-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_student_examiners_student_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='examiners',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password456', max_length=128),
            preserve_default=False,
        ),
    ]
