# Generated by Django 5.1.1 on 2024-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_student_examiners_remove_student_mentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_depth_of_understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_exceptional_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_viva_voce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examiner_work_done_and_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='depth_of_understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='exceptional_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='viva_voce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='work_done_and_results',
            field=models.IntegerField(default=0),
        ),
    ]
