# Generated by Django 5.1.1 on 2024-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password456', max_length=128),
            preserve_default=False,
        ),
    ]
