# Generated by Django 5.1.1 on 2024-10-03 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_depth_of_understanding',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_exceptional_work',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_presentation',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_report',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_viva_voce',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examiner_work_done_and_results',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheet',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner1_endmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner2_endmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner2_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner3_endmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='examiner3_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='professor_endmarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='professor_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='attendance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='depth_of_understanding',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='exceptional_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='presentation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='presentation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='report',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='viva_voce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='work_done_and_results',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='presentation_date',
            field=models.DateField(null=True),
        ),
    ]
