# Generated by Django 4.2.6 on 2024-10-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_marksheet_examiner_depth_of_understanding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
