# Generated by Django 4.2.6 on 2024-10-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0014_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='examiner1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner1_endmarks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner1_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner2_endmarks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner2_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner3_endmarks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='examiner3_marks',
        ),
        migrations.CreateModel(
            name='ExaminerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examiner_marks', models.IntegerField(default=0)),
                ('examiner_endmarks', models.IntegerField(default=0)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
            options={
                'unique_together': {('student', 'examiner')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='examiners',
            field=models.ManyToManyField(related_name='examined_students', through='mainapp.ExaminerAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
