# Generated by Django 4.2.6 on 2024-10-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_student_examiner1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerassignment',
            name='submission_status',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted')], default='Not Submitted', max_length=20),
        ),
    ]
