# Generated by Django 4.2.6 on 2024-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_examinerassignment_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerassignment',
            name='submission_endstatus',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted')], default='Not Submitted', max_length=20),
        ),
    ]
