# Generated by Django 4.2.6 on 2024-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_examinerassignment_submission_endstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submission_endstatus',
            field=models.CharField(choices=[('green', 'Submitted'), ('red', 'Not Submitted')], default='red', max_length=10),
        ),
    ]
