# Generated by Django 4.2.6 on 2024-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_student_submission_endstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='nopw123@', max_length=128),
        ),
    ]
